kind: Deployment
apiVersion: apps/v1
metadata:
  name: mykafka-producer
spec:
  selector:
    matchLabels:
      app: lbl-mykafka-producer
  replicas: 1
  template: 
    metadata:
      labels:
        app: lbl-mykafka-producer
    spec:
      containers:
      - name: cont-mykafka-producer
        image: eitanya/mykafka-producer:latest
        env:
        - name: bootstrap.servers
          value: kafka:9092
        - name: TOPIC
          value: mytopic
